name: Release

on:
  push:
    tags:
      - 'day*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build ${{matrix.os}}
    runs-on: ${{matrix.os}}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows]

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        default: true
    - run: cargo build --release
    - uses: actions/upload-artifact@v2
      with:
        name: adventofcode2020-${{matrix.os}}
        path: target/release/adventofcode*

  release:
    needs: build
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        path: ~/artifacts
    - run: ls -la ~/artifacts/*
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ~/artifacts/adventofcode2020-ubuntu/adventofcode2020
          ~/artifacts/adventofcode2020-windows/adventofcode2020.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
