name: Release

on:
  push:
    tags:
      - 'day*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build ${{matrix.os}}
    runs-on: ${{matrix.os}}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows]

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        default: true
    - run: cargo build --release
    - uses: actions/upload-artifact@v2
      with:
        name: adventofcode2020-${{matrix.os}}
        path: target/release/adventofcode*

  release:
    needs: build
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - uses: actions/download-artifact@v2
      with:
        path: ~/artifacts
    - run: ls -la ~/artifacts/*
    - name: Upload Linux
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ~/artifacts/adventofcode2020-linux
        asset_name: aoc2020-linux-x86_64
        asset_content_type: application/octet-stream
    - name: Upload Windows
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ~/artifacts/adventofcode2020-windows
        asset_name: aoc2020-windows-x86_64.exe
        asset_content_type: application/octet-stream
