name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        default: true
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: x86_64-pc-windows-msvc
        override: true
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: test
        args: --target x86_64-pc-windows-msvc --release
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --target x86_64-pc-windows-msvc --release

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: x86_64-apple-darwin
        override: true
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: test
        args: --target x86_64-apple-darwin --release
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --target x86_64-apple-darwin --release
