name: Test

on:
  push:
    paths-ignore:
    - 'js/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        default: true
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: x86_64-pc-windows-gnu
        override: true
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: test
        args: --target x86_64-pc-windows-gnu --release
